2021-10-05 22:49:20,291 INFO    MainThread:343638 [wandb_setup.py:_flush():69] setting env: {}
2021-10-05 22:49:20,291 INFO    MainThread:343638 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-05 22:49:20,291 INFO    MainThread:343638 [wandb_init.py:_log_setup():342] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Intel-Image-Clf-V2/wandb/run-20211005_224920-3dy910bc/logs/debug.log
2021-10-05 22:49:20,291 INFO    MainThread:343638 [wandb_init.py:_log_setup():343] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Intel-Image-Clf-V2/wandb/run-20211005_224920-3dy910bc/logs/debug-internal.log
2021-10-05 22:49:20,291 INFO    MainThread:343638 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f2ae4268090>
2021-10-05 22:49:20,292 INFO    MainThread:343638 [wandb_init.py:init():375] calling init triggers
2021-10-05 22:49:20,292 INFO    MainThread:343638 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-10-05 22:49:20,292 INFO    MainThread:343638 [wandb_init.py:init():397] re-initializing run, found existing run on stack: 32dh4yqb
2021-10-05 22:49:20,293 INFO    MainThread:343638 [wandb_run.py:finish():1271] finishing run ranuga-d/Intel-Image-Clf-V2/32dh4yqb
2021-10-05 22:49:20,293 INFO    MainThread:343638 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-10-05 22:49:20,293 INFO    MainThread:343638 [wandb_run.py:_restore():1543] restore
2021-10-05 22:49:21,025 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 718
}

2021-10-05 22:49:21,588 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 718
}

2021-10-05 22:49:22,523 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24168
}

2021-10-05 22:49:22,626 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24249
}

2021-10-05 22:49:22,729 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24249
}

2021-10-05 22:49:22,830 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24249
}

2021-10-05 22:49:22,931 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24249
}

2021-10-05 22:49:23,038 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24249
}

2021-10-05 22:49:23,139 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24249
}

2021-10-05 22:49:23,241 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 718
  total_bytes: 24249
}

2021-10-05 22:49:23,343 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24249
  total_bytes: 24249
}

2021-10-05 22:49:23,445 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24249
  total_bytes: 24249
}

2021-10-05 22:49:23,547 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24249
  total_bytes: 24249
}

2021-10-05 22:49:23,648 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24249
  total_bytes: 24249
}

2021-10-05 22:49:23,749 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24249
  total_bytes: 24249
}

2021-10-05 22:49:23,850 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24249
  total_bytes: 24249
}

2021-10-05 22:49:23,952 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24249
  total_bytes: 24249
}

2021-10-05 22:49:24,053 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24249
  total_bytes: 24249
}

2021-10-05 22:49:24,536 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24249
  total_bytes: 24249
}

2021-10-05 22:49:24,638 INFO    MainThread:343638 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 24249
  total_bytes: 24249
}

2021-10-05 22:49:25,730 INFO    MainThread:343638 [wandb_run.py:_show_files():1915] logging synced files
2021-10-05 22:49:25,733 INFO    MainThread:343638 [wandb_init.py:init():424] starting backend
2021-10-05 22:49:25,733 INFO    MainThread:343638 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-05 22:49:25,735 INFO    MainThread:343638 [backend.py:ensure_launched():135] starting backend process...
2021-10-05 22:49:25,785 INFO    MainThread:343638 [backend.py:ensure_launched():140] started backend process with pid: 345901
2021-10-05 22:49:25,786 INFO    MainThread:343638 [wandb_init.py:init():429] backend started and connected
2021-10-05 22:49:25,796 INFO    MainThread:343638 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-10-05 22:49:25,798 INFO    MainThread:343638 [wandb_init.py:init():477] updated telemetry
2021-10-05 22:49:25,798 INFO    MainThread:343638 [wandb_init.py:init():500] communicating current version
2021-10-05 22:49:26,884 INFO    MainThread:343638 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-10-05 22:49:26,885 INFO    MainThread:343638 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-10-05 22:49:27,378 INFO    MainThread:343638 [wandb_init.py:init():540] starting run threads in backend
2021-10-05 22:49:32,386 INFO    MainThread:343638 [wandb_run.py:_console_start():1601] atexit reg
2021-10-05 22:49:32,387 INFO    MainThread:343638 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-10-05 22:49:32,387 INFO    MainThread:343638 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-10-05 22:49:32,388 INFO    MainThread:343638 [wandb_run.py:_redirect():1536] Redirects installed.
2021-10-05 22:49:32,388 INFO    MainThread:343638 [wandb_init.py:init():565] run started, returning control to user process
2021-10-05 22:49:32,410 INFO    MainThread:343638 [wandb_init.py:_pause_backend():256] pausing backend
2021-10-05 22:49:32,410 INFO    MainThread:343638 [jupyter.py:save_ipynb():301] looking for notebook: 00.ipynb
2021-10-05 22:49:32,904 INFO    MainThread:343638 [wandb_init.py:_pause_backend():260] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7f2ae4257590>
2021-10-05 22:49:48,277 INFO    MainThread:343638 [wandb_init.py:_resume_backend():265] resuming backend
2021-10-05 22:49:48,279 INFO    MainThread:343638 [wandb_init.py:_pause_backend():256] pausing backend
2021-10-05 22:49:48,280 INFO    MainThread:343638 [jupyter.py:save_ipynb():301] looking for notebook: 00.ipynb
2021-10-05 22:49:48,786 INFO    MainThread:343638 [wandb_init.py:_pause_backend():260] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7f2c1c1a4890>
2021-10-05 22:49:48,790 INFO    MainThread:343638 [wandb_init.py:_resume_backend():265] resuming backend
2021-10-05 22:49:48,797 INFO    MainThread:343638 [wandb_init.py:_pause_backend():256] pausing backend
2021-10-05 22:49:48,797 INFO    MainThread:343638 [jupyter.py:save_ipynb():301] looking for notebook: 00.ipynb
2021-10-05 22:49:49,268 INFO    MainThread:343638 [wandb_init.py:_pause_backend():260] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7f2ae428a9d0>
2021-10-05 22:49:49,273 INFO    MainThread:343638 [wandb_init.py:_resume_backend():265] resuming backend
2021-10-05 22:49:49,280 INFO    MainThread:343638 [wandb_setup.py:_flush():69] setting env: {}
2021-10-05 22:49:49,280 INFO    MainThread:343638 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-05 22:49:49,280 INFO    MainThread:343638 [wandb_init.py:_log_setup():342] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Intel-Image-Clf-V2/wandb/run-20211005_224949-242hiwv0/logs/debug.log
2021-10-05 22:49:49,280 INFO    MainThread:343638 [wandb_init.py:_log_setup():343] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Intel-Image-Clf-V2/wandb/run-20211005_224949-242hiwv0/logs/debug-internal.log
2021-10-05 22:49:49,281 INFO    MainThread:343638 [wandb_init.py:init():375] calling init triggers
2021-10-05 22:49:49,281 INFO    MainThread:343638 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {}
2021-10-05 22:49:49,281 INFO    MainThread:343638 [wandb_init.py:init():397] re-initializing run, found existing run on stack: 3dy910bc
2021-10-05 22:49:49,282 INFO    MainThread:343638 [wandb_run.py:finish():1271] finishing run ranuga-d/Intel-Image-Clf-V2/3dy910bc
